apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-b
spec:
  host: reviews
  subsets:
    - name: servicec-v2
      labels:
        version: v2
      trafficPolicy:
        connectionPool:
          http:
            http1MaxPendingRequests: 10
            maxRequestsPerConnection: 1
          tcp:
            maxConnections: 5
        outlierDetection:
            baseEjectionTime: 50s
            consecutiveErrors: 1
            interval: 25s
            maxEjectionPercent: 100
