apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews2
spec:
  hosts:
  - reviews
  http:
  - fault:
      abort:
        httpStatus: 555
        percentage:
          value: 100
    route:
    - destination:
        host: reviews
        subset: v3
  - route:
    - destination:
        host: reviews
        subset: v3
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews2
spec:
  host: reviews2
  subsets:
  - name: v3
    labels:
      version: v3
