apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviewsfault
spec:
  hosts:
  - reviews
  http:
  - fault:
      abort:
        httpStatus: 555
        percentage:
          value: 100
    route:
    - destination:
        host: reviews
        subset: v2
  - route:
    - destination:
        host: details
        subset: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews2
spec:
  host: reviews
  subsets:
  - name: v2
    labels:
      version: v2
